FROM ubuntu

COPY daemon /files/
COPY zebra_r1.conf /files/
COPY ospfd_r1.conf /files/

RUN export DEBIAN_FRONTEND=noninteractive
RUN apt-get -qq -y update && apt-get -qq -y clean && apt-get -qq -y install quagga quagga-doc

RUN cp /files/daemon etc/quagga/daemon
RUN cp /files/zebra_r1.conf etc/quagga/zebra.conf
RUN cp /files/ospfd_r1.conf etc/quagga/ospfd.conf

RUN echo "net.ipv4.ip_forward=1" >> etc/sysctl.conf

CMD ["bash"]
