FROM ubuntu

COPY daemon /files/
COPY zebra.conf /files/
COPY ospfd_r2.conf /files/

RUN export DEBIAN_FRONTEND=noninteractive
RUN apt-get -qq -y update > null
RUN apt-get -qq -y clean > null
RUN apt-get -qq -y install quagga > null
RUN apt-get -qq -y install bash iproute2 net-tools tcpdump vim iputils-ping > null
RUN apt-get -qq -y install traceroute > null

RUN cp /files/daemon etc/quagga/daemon
RUN cp /files/zebra.conf etc/quagga/zebra.conf
RUN cp /files/ospfd_r2.conf etc/quagga/ospfd.conf

RUN echo "net.ipv4.ip_forward=1" >> etc/sysctl.conf

CMD ["bash"]
