FROM ubuntu

COPY daemon /files/
COPY zebra_r2.conf /files/
COPY ospfd_r2_same.conf /files/
COPY ospfd_r2_light.conf /files/
COPY ospfd_r2_heavy.conf /files/

RUN export DEBIAN_FRONTEND=noninteractive
RUN apt-get -qq -y update > null
RUN apt-get -qq -y clean > null
RUN apt-get -qq -y install quagga > null

RUN cp /files/daemon etc/quagga/daemon
RUN cp /files/zebra_r2.conf etc/quagga/zebra.conf
RUN cp /files/ospfd_r2_same.conf etc/quagga/ospfd.conf

RUN echo "net.ipv4.ip_forward=1" >> etc/sysctl.conf

CMD ["bash"]
